//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sekretari_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditori
    {
        public int id_auditori { get; set; }
        public int id_klasa { get; set; }
        public int id_nxenes { get; set; }
        public int id_mesuesi { get; set; }
    
        public virtual Klasa Klasa { get; set; }
        public virtual Mesuesi Mesuesi { get; set; }
        public virtual Nxene Nxene { get; set; }
    }
}
