//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sekretari_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lenda()
        {
            this.Mesuesis = new HashSet<Mesuesi>();
            this.Mungesats = new HashSet<Mungesat>();
            this.Notats = new HashSet<Notat>();
        }
    
        public int id_lenda { get; set; }
        public string emri_lendes { get; set; }
        public string oret_javore { get; set; }
        public Nullable<int> semestri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesuesi> Mesuesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mungesat> Mungesats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notat> Notats { get; set; }
    }
}
