//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sekretari_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mungesat
    {
        public int id_mungesa { get; set; }
        public int id_nxenes { get; set; }
        public int id_lenda { get; set; }
        public Nullable<int> Nr_Mungesave { get; set; }
    
        public virtual Lenda Lenda { get; set; }
        public virtual Nxene Nxene { get; set; }
    }
}
