//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sekretari_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notat
    {
        public int id_nota { get; set; }
        public int id_nxenes { get; set; }
        public int id_lenda { get; set; }
        public string Nota { get; set; }
    
        public virtual Lenda Lenda { get; set; }
        public virtual Nxene Nxene { get; set; }
    }
}
